modLoader="javafml"
loaderVersion="[44,)"
license="MPL-2.0"
issueTrackerURL="https://github.com/Tslat/SmartBrainLib/issues"

[[mods]]
modId="smartbrainlib"
version="1.7.4"
displayName="SmartBrainLib"
logoFile="logo.png"
authors="Tslat"
displayTest="IGNORE_SERVER_VERSION"
description='''
A library mod for smarter Brains and easier usage of the Brain system.
'''

[[dependencies.smartbrainlib]]
modId="forge"
mandatory=true
versionRange="[44,)"
ordering="NONE"
side="BOTH"
[[dependencies.smartbrainlib]]
modId="minecraft"
mandatory=true
versionRange="[1.19.3,)"
ordering="NONE"
side="BOTH"
