modLoader="javafml"
loaderVersion="[43,)"
license="MPL 2.0"
issueTrackerURL="https://github.com/Tslat/SmartBrainLib/issues"

[[mods]]
modId="smartbrainlib"
version="${file.jarVersion}"
displayName="SmartBrainLib"
#updateJSONURL="https://change.me.example.invalid/updates.json"
logoFile="logo.png"
authors="Tslat"
displayTest="IGNORE_SERVER_VERSION"
description='''
A library mod for smarter Brains and easier usage of the Brain system.
'''

[[dependencies.smartbrainlib]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.smartbrainlib]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,)"
    ordering="NONE"
    side="BOTH"
