modLoader="javafml"
loaderVersion="[36,)"
license="MPL 2.0"
issueTrackerURL="https://github.com/Tslat/SmartBrainLib/issues"

[[mods]]
modId="smartbrainlib"
version="1.2"
displayName="SmartBrainLib"
logoFile="logo.png"
authors="Tslat, DerToaster98"
description='''
A library mod for smarter Brains and easier usage of the Brain system.
'''
