modLoader="javafml"
loaderVersion="${neoforge_loader_version_range}"
license="MPL-2.0"
issueTrackerURL="https://github.com/Tslat/SmartBrainLib/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
logoFile="logo.png"
authors="Tslat"
displayTest="IGNORE_SERVER_VERSION"
description='''
A library mod for smarter Brains and easier usage of the Brain system.
'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neoforge_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
